# Generated by Django 4.2.23 on 2025-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.FileField(upload_to='docs')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(default=0, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='news')),
                ('name', models.CharField(max_length=100)),
                ('short_des', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(upload_to='icons')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'In-Progress'), (3, 'Completed')], default=2, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('country', models.SmallIntegerField(choices=[(1, 'Toshkent shahri'), (2, 'Andijon'), (3, 'Buxoro'), (4, 'Fargʻona'), (5, 'Jizzax'), (6, 'Xorazm'), (7, 'Namangan'), (8, 'Navoiy'), (9, 'Qashqadaryo'), (10, 'Qoraqalpogʻiston Respublikasi'), (12, 'Sirdaryo'), (13, 'Surxondaryo'), (14, 'Toshkent viloyati')], max_length=100)),
                ('trans_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('phone', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
