# Generated by Django 4.2.23 on 2025-06-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('picture', 'Picture'), ('video', 'Video')], default='picture', max_length=50),
        ),
    ]
