# Generated by Django 4.2.23 on 2025-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Toshkent shahri'), (2, 'Andijon'), (3, 'Buxoro'), (4, 'Fargʻona'), (5, 'Jizzax'), (6, 'Xorazm'), (7, 'Namangan'), (8, 'Navoiy'), (9, 'Qashqadaryo'), (10, 'Qoraqalpogʻiston Respublikasi'), (12, 'Sirdaryo'), (13, 'Surxondaryo'), (14, 'Toshkent viloyati')], max_length=100, null=True),
        ),
    ]
