# Generated by Django 4.2.23 on 2025-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_gallery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='degree',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('director', 'Director'), ('assistant_director', 'Assistant Director')], default='president', max_length=255, null=True),
        ),
    ]
