# Generated by Django 5.2.5 on 2025-08-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='employee')),
                ('full_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('work_time_from', models.TimeField()),
                ('work_time_to', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
