# Generated by Django 5.2.5 on 2025-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Haydovchi'), (2, 'Yuridik Shaxs')], default=1),
        ),
    ]
