# Generated by Django 4.2.23 on 2025-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_faq_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
