# Generated by Django 5.2.5 on 2025-08-26 06:54

import apps.common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Haydovchi'), (2, 'Yuridik Shaxs'), (3, 'Boshqa')], default=1),
        ),
        migrations.CreateModel(
            name='UserVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expires_at', models.DateTimeField(default=apps.common.utils.two_minutes_from_now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='common.user')),
            ],
        ),
    ]
