# Generated by Django 4.2.23 on 2025-06-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_clubmember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='common.clubmember'),
        ),
    ]
