# Generated by Django 4.2.23 on 2025-06-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_metric_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='common.clubmember'),
        ),
    ]
