# Generated by Django 4.2.23 on 2025-06-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_sociallink_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='title_uz',
        ),
    ]
