# Generated by Django 5.2.5 on 2025-08-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_carrierpreference_companyprofile_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='common.user'),
            preserve_default=False,
        ),
    ]
