# Generated by Django 4.2.23 on 2025-06-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_travel_title_en_remove_travel_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoandaudio',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.clubmember'),
        ),
        migrations.AlterField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.gallery'),
        ),
        migrations.AlterField(
            model_name='images',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.news'),
        ),
        migrations.AlterField(
            model_name='images',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.travel'),
        ),
        migrations.AlterField(
            model_name='videoandaudio',
            name='speakers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.speaker'),
        ),
    ]
