# Generated by Django 5.2.5 on 2025-08-26 12:19

import apps.common.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_trailer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Murojaat', 'verbose_name_plural': 'Murojaatlar'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Tashkilot profili', 'verbose_name_plural': 'Tashkilot profillari'},
        ),
        migrations.AlterModelOptions(
            name='consent',
            options={'verbose_name': 'Rozilik', 'verbose_name_plural': 'Roziliklar'},
        ),
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Hujjat', 'verbose_name_plural': 'Hujjatlar'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='membershipapplication',
            options={'verbose_name': 'Aʼzolik arizasi', 'verbose_name_plural': 'Aʼzolik arizalari'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='personprofile',
            options={'verbose_name': 'Jismoniy shaxs profili', 'verbose_name_plural': 'Jismoniy shaxs profillari'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'verbose_name': 'Tirkama', 'verbose_name_plural': 'Tirkamalar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='userdoc',
            options={'verbose_name': 'Foydalanuvchi hujjati', 'verbose_name_plural': 'Foydalanuvchi hujjatlari'},
        ),
        migrations.AlterModelOptions(
            name='userverificationcode',
            options={'verbose_name': 'Tasdiqlash kodi', 'verbose_name_plural': 'Tasdiqlash kodlari'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Transport vositasi', 'verbose_name_plural': 'Transport vositalari'},
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Biriktirilgan fayl'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='To‘liq ism-sharif'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='cargo_types',
            field=models.JSONField(default=list, help_text='CargoType qiymatlari ro‘yxati (masalan: [1,2,3])', verbose_name='Asosiy yuk turlari (ID ro‘yxati)'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='international_routes',
            field=models.TextField(blank=True, help_text="Masalan: O'zbekiston–Qozog'iston; O'zbekiston–Rossiya ...", null=True, verbose_name='Xalqaro yo‘nalishlar'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='primary_route_1',
            field=models.CharField(max_length=150, verbose_name='Asosiy yo‘nalish 1'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='primary_route_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Asosiy yo‘nalish 2'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='primary_route_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Asosiy yo‘nalish 3'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='scope',
            field=models.SmallIntegerField(choices=[(1, 'Respublika bo‘yicha'), (2, 'Xalqaro')], verbose_name='Yo‘nalish turi'),
        ),
        migrations.AlterField(
            model_name='carrierpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='director_full_name',
            field=models.CharField(max_length=150, verbose_name='Rahbarning F.I.Sh.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='drivers_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Haydovchilar soni'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='employees_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy xodimlar soni'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', "STIR/INN 9–12 xonali bo'lishi kerak.")], verbose_name='STIR'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='legal_address',
            field=models.CharField(max_length=255, verbose_name='Yuridik manzil'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+?998|998)?\\s?\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$', "Telefon raqamini +998 ** ** ** ** ko'rinishida kiriting.")], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='registered_at',
            field=models.DateField(blank=True, null=True, verbose_name='Roʻyxatdan oʻtgan sana'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='responsible_full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Masʼul vakil F.I.Sh.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='stability_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Barqarorlik reytingi (0–5)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Veb-sayt'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='charter_agreed',
            field=models.BooleanField(default=False, help_text='Uyushma Ustavini o‘qib, rozilik', verbose_name='«Uyushma Ustavini o‘qidim va roziman»'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='personal_data_processing',
            field=models.BooleanField(default=False, help_text='Shaxsiy maʼlumotlarni qayta ishlashga rozilik', verbose_name='«Shaxsiy maʼlumotlarimni qayta ishlashga roziman»'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='icon',
            field=models.FileField(upload_to='docs', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='size',
            field=models.CharField(default=0, max_length=100, verbose_name='Hajm (MB)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Lavozim / daraja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.Sh.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_time_from',
            field=models.TimeField(verbose_name='Ish vaqti (dan)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_time_to',
            field=models.TimeField(verbose_name='Ish vaqti (gacha)'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='applications', verbose_name='Biriktirilgan fayl'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='To‘liq ism-sharif'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+?998|998)?\\s?\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$', "Telefon raqamini +998 ** ** ** ** ko'rinishida kiriting.")], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(default='new', max_length=30, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_des',
            field=models.CharField(max_length=255, verbose_name='Qisqa taʼrif'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugʻilgan sana'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(\\+?998|998)?\\s?\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$', "Telefon raqamini +998 ** ** ** ** ko'rinishida kiriting.")], verbose_name='Qoʻshimcha telefon'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='has_international_visa',
            field=models.BooleanField(default=False, verbose_name='Xalqaro viza mavjud'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='house',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Uy'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='passport_given_at',
            field=models.DateField(blank=True, null=True, verbose_name='Pasport berilgan sana'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='passport_issuer',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Beruvchi organ'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='passport_number',
            field=models.CharField(blank=True, help_text='AA1234567', max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{7}$', "Pasport seriya va raqami (masalan, AA1234567) ko'rinishida bo'lishi kerak.")], verbose_name='Pasport seriyasi va raqami'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='region',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Toshkent shahri'), (2, 'Andijon'), (3, 'Buxoro'), (4, 'Fargʻona'), (5, 'Jizzax'), (6, 'Xorazm'), (7, 'Namangan'), (8, 'Navoiy'), (9, 'Qashqadaryo'), (10, 'Qoraqalpogʻiston Respublikasi'), (12, 'Sirdaryo'), (13, 'Surxondaryo'), (14, 'Toshkent viloyati')], null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Koʻcha'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='workplace_inn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,12}$', "STIR/INN 9–12 xonali bo'lishi kerak.")], verbose_name='Ish joyi STIR'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='workplace_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ish joyi (tashkilot nomi)'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Ish tajribasi (yil)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='des',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Piktogramma'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Piktogramma nomi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Xizmat nomi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Faol'), (2, 'Jarayonda'), (3, 'Yakunlangan')], default=2, max_length=100, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='brand',
            field=models.CharField(max_length=80, verbose_name='Tirkama markasi'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='capacity_tons',
            field=models.DecimalField(decimal_places=2, help_text='tonnada', max_digits=6, verbose_name='Yuk ko‘tarish sig‘imi (t)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='manufactured_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2026)], verbose_name='Ishlab chiqarilgan yili'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='model',
            field=models.CharField(max_length=80, verbose_name='Modeli'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Davlat raqami'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='tech_passport_number',
            field=models.CharField(max_length=50, verbose_name='Texnik pasport raqami'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='common.user', verbose_name='Ega (foydalanuvchi)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='common.vehicle', verbose_name='Asosiy transport vositasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Toshkent shahri'), (2, 'Andijon'), (3, 'Buxoro'), (4, 'Fargʻona'), (5, 'Jizzax'), (6, 'Xorazm'), (7, 'Namangan'), (8, 'Navoiy'), (9, 'Qashqadaryo'), (10, 'Qoraqalpogʻiston Respublikasi'), (12, 'Sirdaryo'), (13, 'Surxondaryo'), (14, 'Toshkent viloyati')], null=True, verbose_name='Hudud (viloyat)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Toʻliq ism-sharif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='STIR'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trans_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tashuvlar soni'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Haydovchi'), (2, 'Yuridik shaxs'), (3, 'Boshqa')], default=1, verbose_name='Foydalanuvchi turi'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='document_type',
            field=models.SmallIntegerField(choices=[(1, 'Pasport nusxasi'), (2, 'Haydovchilik guvohnomasi'), (3, 'Transport texnik pasporti'), (4, 'Korxona guvohnomasi'), (5, 'Dazvol'), (6, 'Litsenziya'), (7, 'Sug‘urta polis'), (8, 'Boshqa hujjat')], verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_docs', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Tasdiqlash kodi'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='expires_at',
            field=models.DateTimeField(default=apps.common.utils.two_minutes_from_now, verbose_name='Amal qilish muddati'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='common.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=80, verbose_name='Avtomobil markasi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.SmallIntegerField(choices=[(1, 'Benzin'), (2, 'Dizel'), (3, 'Gaz'), (4, 'Elektr'), (5, 'Gibrid')], verbose_name='Yoqilgʻi turi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sugʻurta polisi raqami'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Sugʻurta amal qilish sanasi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufactured_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2026)], verbose_name='Ishlab chiqarilgan yili'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=80, verbose_name='Modeli'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='common.user', verbose_name='Ega (foydalanuvchi)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Davlat raqami'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tech_passport_number',
            field=models.CharField(max_length=50, verbose_name='Texnik pasport raqami'),
        ),
    ]
