# Generated by Django 5.2.5 on 2025-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons', verbose_name='Piktogramma'),
        ),
    ]
