# Generated by Django 4.2.23 on 2025-06-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_company_remove_clubmember_company_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(),
        ),
    ]
