# Generated by Django 4.2.23 on 2025-06-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_sociallink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
