# Generated by Django 5.2.5 on 2025-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='name',
            field=models.CharField(max_length=555, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=555, verbose_name='Sarlavha'),
        ),
    ]
