# Generated by Django 4.2.23 on 2025-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
