# Generated by Django 4.2.23 on 2025-06-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_tag_name_en_remove_tag_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobiography',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autobiographies', to='common.clubmember'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='business_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_info', to='common.businesscourse'),
        ),
    ]
