# Generated by Django 4.2.23 on 2025-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_autobiography_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobiography',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
