# Generated by Django 4.2.23 on 2025-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_autobiography_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
