# Generated by Django 4.2.23 on 2025-06-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_events_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='common.events')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.speaker')),
            ],
        ),
    ]
