# Generated by Django 4.2.23 on 2025-06-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventagenda',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='common.events'),
        ),
    ]
