# Generated by Django 4.2.23 on 2025-06-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_eventagenda_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoandaudio',
            name='speakers',
        ),
        migrations.CreateModel(
            name='PodcastSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts_speaker', to='common.videoandaudio')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts_speaker', to='common.speaker')),
            ],
        ),
    ]
