# Generated by Django 4.2.23 on 2025-06-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_remove_videoandaudio_speakers_podcastspeaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoandaudio',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.clubmember'),
        ),
    ]
