# Generated by Django 4.2.23 on 2025-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_videoandaudio_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoandaudio',
            name='extra_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoandaudio',
            name='url',
            field=models.URLField(),
        ),
    ]
