# Generated by Django 4.2.23 on 2025-06-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_videoandaudio_extra_image_alter_videoandaudio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.gallery'),
        ),
        migrations.AlterField(
            model_name='images',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.news'),
        ),
        migrations.AlterField(
            model_name='images',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='common.travel'),
        ),
    ]
