# Generated by Django 4.2.23 on 2025-06-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_uploader_created_at_uploader_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='type',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('member', 'Member'), ('expert', 'Expert')], default='attendee', max_length=50),
        ),
    ]
