# Generated by Django 4.2.23 on 2025-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_contactform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='annual_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
