# Generated by Django 4.2.23 on 2025-06-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_alter_contactform_annual_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='business_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_choices', to='common.genericchoice'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_type_choices', to='common.genericchoice'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='employee_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_count_choices', to='common.genericchoice'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='project_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_count_choices', to='common.genericchoice'),
        ),
    ]
