# Generated by Django 4.2.23 on 2025-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_alter_contactform_business_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_revenue', models.URLField()),
                ('club_members', models.URLField()),
                ('business_fields', models.URLField()),
                ('export_scope', models.URLField()),
                ('experience_years', models.URLField()),
            ],
        ),
    ]
