# Generated by Django 4.2.23 on 2025-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_homestaticons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('been', 'Been')], default='waiting', max_length=20),
        ),
    ]
