# Generated by Django 4.2.23 on 2025-06-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_travel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcountry',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='icon',
            field=models.URLField(),
        ),
    ]
