# Generated by Django 4.2.23 on 2025-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_travelcountry_icon_alter_industry_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_zoom',
            field=models.BooleanField(default=False),
        ),
    ]
