# Generated by Django 4.2.23 on 2025-06-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_events_is_zoom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='link',
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='type',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('expert', 'Expert')], default='member', max_length=255, null=True),
        ),
    ]
