# Generated by Django 4.2.23 on 2025-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_remove_faq_link_alter_clubmember_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscourse',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
