# Generated by Django 4.2.23 on 2025-06-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alter_businesscourse_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='degree',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('director', 'Director'), ('assistant_director', 'Assistant Director')], max_length=255, null=True),
        ),
    ]
