# Generated by Django 4.2.23 on 2025-06-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_alter_clubmember_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobiography',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autobiography',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autobiography',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscourse',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscourse',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesscourse',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='bio_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluboffer',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluboffer',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluboffer',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalvalue',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalvalue',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalvalue',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoandaudio',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoandaudio',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoandaudio',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
