# Generated by Django 4.2.23 on 2025-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_alter_autobiography_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10),
        ),
    ]
