# Generated by Django 4.2.23 on 2025-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_alter_uploader_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='telegram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
